// Code generated by protoc-gen-go. DO NOT EDIT.
// source: attendance_management.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Employee struct {
	EmployeeId           int32    `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	MacAddress           string   `protobuf:"bytes,3,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Employee) Reset()         { *m = Employee{} }
func (m *Employee) String() string { return proto.CompactTextString(m) }
func (*Employee) ProtoMessage()    {}
func (*Employee) Descriptor() ([]byte, []int) {
	return fileDescriptor_e694042a29af7161, []int{0}
}

func (m *Employee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Employee.Unmarshal(m, b)
}
func (m *Employee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Employee.Marshal(b, m, deterministic)
}
func (m *Employee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Employee.Merge(m, src)
}
func (m *Employee) XXX_Size() int {
	return xxx_messageInfo_Employee.Size(m)
}
func (m *Employee) XXX_DiscardUnknown() {
	xxx_messageInfo_Employee.DiscardUnknown(m)
}

var xxx_messageInfo_Employee proto.InternalMessageInfo

func (m *Employee) GetEmployeeId() int32 {
	if m != nil {
		return m.EmployeeId
	}
	return 0
}

func (m *Employee) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Employee) GetMacAddress() string {
	if m != nil {
		return m.MacAddress
	}
	return ""
}

func (m *Employee) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DailyAttendanceLog struct {
	AttendanceId         uint32   `protobuf:"varint,1,opt,name=attendance_id,json=attendanceId,proto3" json:"attendance_id,omitempty"`
	EmployeeId           int32    `protobuf:"varint,2,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	Date                 string   `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	FirstLoggedAt        string   `protobuf:"bytes,4,opt,name=first_logged_at,json=firstLoggedAt,proto3" json:"first_logged_at,omitempty"`
	LastLoggedAt         string   `protobuf:"bytes,5,opt,name=last_logged_at,json=lastLoggedAt,proto3" json:"last_logged_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DailyAttendanceLog) Reset()         { *m = DailyAttendanceLog{} }
func (m *DailyAttendanceLog) String() string { return proto.CompactTextString(m) }
func (*DailyAttendanceLog) ProtoMessage()    {}
func (*DailyAttendanceLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_e694042a29af7161, []int{1}
}

func (m *DailyAttendanceLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DailyAttendanceLog.Unmarshal(m, b)
}
func (m *DailyAttendanceLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DailyAttendanceLog.Marshal(b, m, deterministic)
}
func (m *DailyAttendanceLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DailyAttendanceLog.Merge(m, src)
}
func (m *DailyAttendanceLog) XXX_Size() int {
	return xxx_messageInfo_DailyAttendanceLog.Size(m)
}
func (m *DailyAttendanceLog) XXX_DiscardUnknown() {
	xxx_messageInfo_DailyAttendanceLog.DiscardUnknown(m)
}

var xxx_messageInfo_DailyAttendanceLog proto.InternalMessageInfo

func (m *DailyAttendanceLog) GetAttendanceId() uint32 {
	if m != nil {
		return m.AttendanceId
	}
	return 0
}

func (m *DailyAttendanceLog) GetEmployeeId() int32 {
	if m != nil {
		return m.EmployeeId
	}
	return 0
}

func (m *DailyAttendanceLog) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *DailyAttendanceLog) GetFirstLoggedAt() string {
	if m != nil {
		return m.FirstLoggedAt
	}
	return ""
}

func (m *DailyAttendanceLog) GetLastLoggedAt() string {
	if m != nil {
		return m.LastLoggedAt
	}
	return ""
}

type AddEmployeeRequest struct {
	EmployeeId           int32    `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	MacAddress           string   `protobuf:"bytes,3,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddEmployeeRequest) Reset()         { *m = AddEmployeeRequest{} }
func (m *AddEmployeeRequest) String() string { return proto.CompactTextString(m) }
func (*AddEmployeeRequest) ProtoMessage()    {}
func (*AddEmployeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e694042a29af7161, []int{2}
}

func (m *AddEmployeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddEmployeeRequest.Unmarshal(m, b)
}
func (m *AddEmployeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddEmployeeRequest.Marshal(b, m, deterministic)
}
func (m *AddEmployeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddEmployeeRequest.Merge(m, src)
}
func (m *AddEmployeeRequest) XXX_Size() int {
	return xxx_messageInfo_AddEmployeeRequest.Size(m)
}
func (m *AddEmployeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddEmployeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddEmployeeRequest proto.InternalMessageInfo

func (m *AddEmployeeRequest) GetEmployeeId() int32 {
	if m != nil {
		return m.EmployeeId
	}
	return 0
}

func (m *AddEmployeeRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AddEmployeeRequest) GetMacAddress() string {
	if m != nil {
		return m.MacAddress
	}
	return ""
}

func (m *AddEmployeeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AddEmployeeResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddEmployeeResponse) Reset()         { *m = AddEmployeeResponse{} }
func (m *AddEmployeeResponse) String() string { return proto.CompactTextString(m) }
func (*AddEmployeeResponse) ProtoMessage()    {}
func (*AddEmployeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e694042a29af7161, []int{3}
}

func (m *AddEmployeeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddEmployeeResponse.Unmarshal(m, b)
}
func (m *AddEmployeeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddEmployeeResponse.Marshal(b, m, deterministic)
}
func (m *AddEmployeeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddEmployeeResponse.Merge(m, src)
}
func (m *AddEmployeeResponse) XXX_Size() int {
	return xxx_messageInfo_AddEmployeeResponse.Size(m)
}
func (m *AddEmployeeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddEmployeeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddEmployeeResponse proto.InternalMessageInfo

func (m *AddEmployeeResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AddEmployeeResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetEmployeeRequest struct {
	MacAddress           []string `protobuf:"bytes,1,rep,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEmployeeRequest) Reset()         { *m = GetEmployeeRequest{} }
func (m *GetEmployeeRequest) String() string { return proto.CompactTextString(m) }
func (*GetEmployeeRequest) ProtoMessage()    {}
func (*GetEmployeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e694042a29af7161, []int{4}
}

func (m *GetEmployeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmployeeRequest.Unmarshal(m, b)
}
func (m *GetEmployeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmployeeRequest.Marshal(b, m, deterministic)
}
func (m *GetEmployeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmployeeRequest.Merge(m, src)
}
func (m *GetEmployeeRequest) XXX_Size() int {
	return xxx_messageInfo_GetEmployeeRequest.Size(m)
}
func (m *GetEmployeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmployeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmployeeRequest proto.InternalMessageInfo

func (m *GetEmployeeRequest) GetMacAddress() []string {
	if m != nil {
		return m.MacAddress
	}
	return nil
}

type GetEmployeeResponse struct {
	Employees            []*Employee `protobuf:"bytes,1,rep,name=employees,proto3" json:"employees,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetEmployeeResponse) Reset()         { *m = GetEmployeeResponse{} }
func (m *GetEmployeeResponse) String() string { return proto.CompactTextString(m) }
func (*GetEmployeeResponse) ProtoMessage()    {}
func (*GetEmployeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e694042a29af7161, []int{5}
}

func (m *GetEmployeeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmployeeResponse.Unmarshal(m, b)
}
func (m *GetEmployeeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmployeeResponse.Marshal(b, m, deterministic)
}
func (m *GetEmployeeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmployeeResponse.Merge(m, src)
}
func (m *GetEmployeeResponse) XXX_Size() int {
	return xxx_messageInfo_GetEmployeeResponse.Size(m)
}
func (m *GetEmployeeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmployeeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmployeeResponse proto.InternalMessageInfo

func (m *GetEmployeeResponse) GetEmployees() []*Employee {
	if m != nil {
		return m.Employees
	}
	return nil
}

type EmployeeAttendanceRequest struct {
	EmployeeId           int32    `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmployeeAttendanceRequest) Reset()         { *m = EmployeeAttendanceRequest{} }
func (m *EmployeeAttendanceRequest) String() string { return proto.CompactTextString(m) }
func (*EmployeeAttendanceRequest) ProtoMessage()    {}
func (*EmployeeAttendanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e694042a29af7161, []int{6}
}

func (m *EmployeeAttendanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmployeeAttendanceRequest.Unmarshal(m, b)
}
func (m *EmployeeAttendanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmployeeAttendanceRequest.Marshal(b, m, deterministic)
}
func (m *EmployeeAttendanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmployeeAttendanceRequest.Merge(m, src)
}
func (m *EmployeeAttendanceRequest) XXX_Size() int {
	return xxx_messageInfo_EmployeeAttendanceRequest.Size(m)
}
func (m *EmployeeAttendanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmployeeAttendanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmployeeAttendanceRequest proto.InternalMessageInfo

func (m *EmployeeAttendanceRequest) GetEmployeeId() int32 {
	if m != nil {
		return m.EmployeeId
	}
	return 0
}

type EmployeeAttendanceResponse struct {
	Success              bool                `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string              `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AttendanceLog        *DailyAttendanceLog `protobuf:"bytes,3,opt,name=attendance_log,json=attendanceLog,proto3" json:"attendance_log,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *EmployeeAttendanceResponse) Reset()         { *m = EmployeeAttendanceResponse{} }
func (m *EmployeeAttendanceResponse) String() string { return proto.CompactTextString(m) }
func (*EmployeeAttendanceResponse) ProtoMessage()    {}
func (*EmployeeAttendanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e694042a29af7161, []int{7}
}

func (m *EmployeeAttendanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmployeeAttendanceResponse.Unmarshal(m, b)
}
func (m *EmployeeAttendanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmployeeAttendanceResponse.Marshal(b, m, deterministic)
}
func (m *EmployeeAttendanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmployeeAttendanceResponse.Merge(m, src)
}
func (m *EmployeeAttendanceResponse) XXX_Size() int {
	return xxx_messageInfo_EmployeeAttendanceResponse.Size(m)
}
func (m *EmployeeAttendanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmployeeAttendanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmployeeAttendanceResponse proto.InternalMessageInfo

func (m *EmployeeAttendanceResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *EmployeeAttendanceResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *EmployeeAttendanceResponse) GetAttendanceLog() *DailyAttendanceLog {
	if m != nil {
		return m.AttendanceLog
	}
	return nil
}

func init() {
	proto.RegisterType((*Employee)(nil), "Employee")
	proto.RegisterType((*DailyAttendanceLog)(nil), "DailyAttendanceLog")
	proto.RegisterType((*AddEmployeeRequest)(nil), "AddEmployeeRequest")
	proto.RegisterType((*AddEmployeeResponse)(nil), "AddEmployeeResponse")
	proto.RegisterType((*GetEmployeeRequest)(nil), "GetEmployeeRequest")
	proto.RegisterType((*GetEmployeeResponse)(nil), "GetEmployeeResponse")
	proto.RegisterType((*EmployeeAttendanceRequest)(nil), "EmployeeAttendanceRequest")
	proto.RegisterType((*EmployeeAttendanceResponse)(nil), "EmployeeAttendanceResponse")
}

func init() { proto.RegisterFile("attendance_management.proto", fileDescriptor_e694042a29af7161) }

var fileDescriptor_e694042a29af7161 = []byte{
	// 451 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x94, 0x51, 0x8b, 0xd3, 0x40,
	0x10, 0xc7, 0xc9, 0x5d, 0xab, 0xd7, 0x69, 0x7b, 0x07, 0x93, 0x0a, 0x31, 0xf7, 0x60, 0x89, 0xa2,
	0xf7, 0xb4, 0x07, 0x15, 0x41, 0x45, 0x84, 0x8a, 0x22, 0x85, 0x3e, 0x1c, 0xf1, 0xcd, 0x97, 0xb0,
	0x66, 0xc7, 0x10, 0xc9, 0x66, 0x6b, 0x76, 0xef, 0xe0, 0xde, 0xfc, 0x00, 0x7e, 0x24, 0x3f, 0x88,
	0x1f, 0x47, 0xb2, 0xcd, 0x5e, 0x53, 0x93, 0x03, 0xf1, 0xe1, 0x9e, 0xba, 0xf3, 0x9f, 0x99, 0xee,
	0x6f, 0xff, 0x33, 0x04, 0x4e, 0xb9, 0x31, 0x54, 0x0a, 0x5e, 0xa6, 0x94, 0x48, 0x5e, 0xf2, 0x8c,
	0x24, 0x95, 0x86, 0x6d, 0x2a, 0x65, 0x54, 0x74, 0x05, 0x47, 0x1f, 0xe4, 0xa6, 0x50, 0xd7, 0x44,
	0xf8, 0x08, 0xc6, 0xd4, 0x9c, 0x93, 0x5c, 0x04, 0xde, 0xdc, 0x3b, 0x1b, 0xc6, 0xe0, 0xa4, 0x95,
	0xc0, 0x19, 0x0c, 0x49, 0xf2, 0xbc, 0x08, 0x0e, 0xe6, 0xde, 0xd9, 0x28, 0xde, 0x06, 0x75, 0x9b,
	0xe4, 0x69, 0xc2, 0x85, 0xa8, 0x48, 0xeb, 0xe0, 0xd0, 0xe6, 0x40, 0xf2, 0x74, 0xb9, 0x55, 0x10,
	0x61, 0x50, 0x72, 0x49, 0xc1, 0xc0, 0x66, 0xec, 0x39, 0xfa, 0xe5, 0x01, 0xbe, 0xe7, 0x79, 0x71,
	0xbd, 0xbc, 0x81, 0x5b, 0xab, 0x0c, 0x1f, 0xc3, 0xb4, 0x45, 0xdb, 0x40, 0x4c, 0xe3, 0xc9, 0x4e,
	0x5c, 0x89, 0xbf, 0x39, 0x0f, 0x3a, 0x9c, 0x08, 0x03, 0xc1, 0x0d, 0x35, 0x28, 0xf6, 0x8c, 0x4f,
	0xe1, 0xe4, 0x6b, 0x5e, 0x69, 0x93, 0x14, 0x2a, 0xcb, 0x48, 0x24, 0xdc, 0x34, 0x3c, 0x53, 0x2b,
	0xaf, 0xad, 0xba, 0x34, 0xf8, 0x04, 0x8e, 0x0b, 0xbe, 0x57, 0x36, 0xb4, 0x65, 0x93, 0x5a, 0x75,
	0x55, 0xd1, 0x0f, 0x0f, 0x70, 0x29, 0x84, 0xb3, 0x2e, 0xa6, 0xef, 0x97, 0xa4, 0xcd, 0x9d, 0x3a,
	0xb8, 0x02, 0x7f, 0x8f, 0x40, 0x6f, 0x54, 0xa9, 0x09, 0x03, 0xb8, 0xaf, 0x2f, 0xd3, 0xb4, 0xfe,
	0x9f, 0xfa, 0xfa, 0xa3, 0xd8, 0x85, 0x75, 0x46, 0x92, 0xd6, 0x3c, 0xa3, 0xe6, 0x76, 0x17, 0x46,
	0x2f, 0x00, 0x3f, 0x92, 0xe9, 0x79, 0x4c, 0x9b, 0xca, 0x9b, 0x1f, 0xee, 0x53, 0x45, 0x6f, 0xc1,
	0xdf, 0x6b, 0x6b, 0x08, 0x9e, 0xc1, 0xc8, 0xbd, 0x78, 0xdb, 0x35, 0x5e, 0x8c, 0xd8, 0x4d, 0xd5,
	0x2e, 0x17, 0xbd, 0x81, 0x87, 0x4e, 0xde, 0x6d, 0xc1, 0xbf, 0x5a, 0x19, 0xfd, 0xf4, 0x20, 0xec,
	0x6b, 0xff, 0x7f, 0x1f, 0xf0, 0x35, 0x1c, 0xb7, 0xb6, 0xaf, 0x50, 0x99, 0x1d, 0xc5, 0x78, 0xe1,
	0xb3, 0xee, 0xaa, 0xc6, 0xad, 0x45, 0x5d, 0xab, 0x6c, 0xf1, 0xdb, 0x83, 0x13, 0x87, 0xf3, 0x89,
	0xaa, 0xab, 0x3c, 0x25, 0x7c, 0x09, 0xe3, 0xd6, 0x88, 0xd0, 0x67, 0xdd, 0x95, 0x09, 0x67, 0xac,
	0x6f, 0x8a, 0xaf, 0x60, 0xd2, 0xb2, 0x56, 0xa3, 0xcf, 0xba, 0x03, 0x0a, 0x67, 0xac, 0xcf, 0xfe,
	0x0b, 0x78, 0xb0, 0x56, 0x59, 0xd7, 0x19, 0x0c, 0xd9, 0xad, 0x6e, 0x87, 0xa7, 0xec, 0x76, 0x2b,
	0xdf, 0xcd, 0x3e, 0xe3, 0x86, 0xcc, 0x45, 0xa5, 0xbe, 0x9d, 0xeb, 0x2a, 0x3d, 0xb7, 0x1f, 0x0e,
	0xfd, 0xe5, 0x9e, 0xfd, 0x7d, 0xfe, 0x27, 0x00, 0x00, 0xff, 0xff, 0xc1, 0xd0, 0x8e, 0x1d, 0x5f,
	0x04, 0x00, 0x00,
}
